### ISSUE TITLE
hi 这里有一个BUG

### ISSUE THREAD

**Issue by shenlilin-libiao** [colin-chang/RedisHelper#3]
![image](https://user-images.githubusercontent.com/32668092/106149685-839cd380-61b5-11eb-93f8-a9c08cbdde45.png)

扩展方法：ToRedisValue<T> 其中泛型类型T没有设置引用类型约束，使用时传入值类型时，t as string 得到 NULL

**Comment by anan1213095357** [comment]
是的 ，我也碰到了这个bug

**Comment by colin-chang** [comment]
感谢反馈，已修复
